from cDLL import cDLL;
from PrimitiveTypes import *;
from StructureTypes import *;

KERNEL32 = cDLL("kernel32.dll");

KERNEL32.fDefineFunction(BOOL,    "CloseHandle", HANDLE);
KERNEL32.fDefineFunction(HANDLE,  "CreateToolhelp32Snapshot", DWORD, DWORD);
KERNEL32.fDefineFunction(BOOL,    "K32EnumProcesses", PDWORD, DWORD, PDWORD);
KERNEL32.fDefineFunction(BOOL,    "GenerateConsoleCtrlEvent", DWORD, DWORD);
KERNEL32.fDefineFunction(BOOL,    "GetConsoleMode", HANDLE, PDWORD);
KERNEL32.fDefineFunction(BOOL,    "GetConsoleScreenBufferInfo", HANDLE, PCONSOLE_SCREEN_BUFFER_INFO);
KERNEL32.fDefineFunction(BOOL,    "GetExitCodeProcess", HANDLE, LPDWORD);
KERNEL32.fDefineFunction(DWORD,   "GetLastError");
KERNEL32.fDefineFunction(HANDLE,  "GetProcessHeap");
KERNEL32.fDefineFunction(DWORD,   "GetShortPathNameA", LPCSTR, LPSTR, DWORD);
KERNEL32.fDefineFunction(DWORD,   "GetShortPathNameW", LPCWSTR, LPWSTR, DWORD);
KERNEL32.fDefineFunction(HANDLE,  "GetStdHandle", DWORD);
KERNEL32.fDefineFunction(LPVOID,  "HeapAlloc", HANDLE, DWORD, SIZE_T);
KERNEL32.fDefineFunction(HANDLE,  "HeapCreate", DWORD, SIZE_T, SIZE_T);
KERNEL32.fDefineFunction(BOOL,    "HeapFree", HANDLE, DWORD, LPVOID);
KERNEL32.fDefineFunction(LPVOID,  "HeapReAlloc", HANDLE, DWORD, LPVOID, SIZE_T);
KERNEL32.fDefineFunction(BOOL,    "Module32First", HANDLE, LPMODULEENTRY32A);
KERNEL32.fDefineFunction(BOOL,    "Module32FirstW", HANDLE, LPMODULEENTRY32W);
KERNEL32.fDefineFunction(BOOL,    "Module32Next", HANDLE, LPMODULEENTRY32A);
KERNEL32.fDefineFunction(BOOL,    "Module32NextW", HANDLE, LPMODULEENTRY32W);
KERNEL32.fDefineFunction(HANDLE,  "OpenProcess", DWORD, BOOL, DWORD);
KERNEL32.fDefineFunction(BOOL,    "OpenProcessToken", HANDLE, DWORD, PHANDLE);
KERNEL32.fDefineFunction(BOOL,    "Process32First", HANDLE, LPPROCESSENTRY32A);
KERNEL32.fDefineFunction(BOOL,    "Process32FirstW", HANDLE, LPPROCESSENTRY32W);
KERNEL32.fDefineFunction(BOOL,    "Process32Next", HANDLE, LPPROCESSENTRY32A);
KERNEL32.fDefineFunction(BOOL,    "Process32NextW", HANDLE, LPPROCESSENTRY32W);
KERNEL32.fDefineFunction(BOOL,    "SetConsoleTextAttribute", HANDLE, WORD);
KERNEL32.fDefineFunction(BOOL,    "TerminateProcess", HANDLE, UINT);
KERNEL32.fDefineFunction(BOOL,    "VirtualProtect", LPVOID, SIZE_T, DWORD, PDWORD);
KERNEL32.fDefineFunction(BOOL,    "VirtualProtectEx", HANDLE, LPVOID, SIZE_T, DWORD, PDWORD);
KERNEL32.fDefineFunction(DWORD,   "WaitForSingleObject", HANDLE, DWORD);
KERNEL32.fDefineFunction(BOOL,    "WriteConsoleA", HANDLE, LPCSTR, DWORD, LPDWORD, LPVOID);
KERNEL32.fDefineFunction(BOOL,    "WriteConsoleW", HANDLE, LPCWSTR, DWORD, LPDWORD, LPVOID);
KERNEL32.fDefineFunction(BOOL,    "WriteFile", HANDLE, LPCVOID, DWORD, LPDWORD, LPOVERLAPPED);
